version: '3.8'

services:
  # MongoDB 
  mongodb:
    image: mongo:latest
    container_name: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017" 

  # Spring Boot
  image-service:
    image: image-service:latest
    container_name: image-service
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    ports:
      - "8080:8080" 
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/image-db

# Automated tests
  tests:
    build: .
    command: mvn test
    depends_on:
      - mongodb

volumes:
  mongo-data: